-- A tabela avaliacao nunca chegou a ser criada: o banco foi baselineado na V1
-- assumindo que o schema já existia (gerado antes por ddl-auto=update), mas
-- essa tabela foi adicionada depois e ficou de fora.
CREATE TABLE avaliacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assistido_id BIGINT NOT NULL,
    numero_vez INTEGER,
    data DATE,
    entrevistador VARCHAR(255),
    historico TEXT,
    evolucao VARCHAR(255),

    CONSTRAINT fk_avaliacao_assistido
        FOREIGN KEY (assistido_id)
        REFERENCES assistido(id)
);

CREATE INDEX idx_avaliacao_assistido ON avaliacao(assistido_id);
