-- Histórico formal de cartões encerrados (item 7 da seção 8 do CLAUDE.md). Até aqui, quando um
-- ciclo terminava (21 dias sem presença, Entrevista abrindo o ciclo seguinte ou troca manual de
-- tratamento), só o "assistido.ciclo_iniciado_em" avançava e o ciclo anterior sumia. Agora cada
-- encerramento vira uma linha, com o tratamento daquele ciclo, o período, as presenças efetivas e
-- como terminou — em especial "INCOMPLETO_POR_TEMPO" ("Tratamento Incompleto") quando expirou.
CREATE TABLE cartao_encerrado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assistido_id BIGINT NOT NULL,
    tratamento_id BIGINT,
    iniciado_em DATE,
    encerrado_em DATE NOT NULL,
    status_final VARCHAR(40) NOT NULL,
    sessoes_efetivas INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_cartao_encerrado_assistido
        FOREIGN KEY (assistido_id) REFERENCES assistido(id) ON DELETE CASCADE,
    CONSTRAINT fk_cartao_encerrado_tratamento
        FOREIGN KEY (tratamento_id) REFERENCES tipo_tratamento(id)
);

CREATE INDEX idx_cartao_encerrado_assistido ON cartao_encerrado (assistido_id);

-- Os ciclos já encerrados antes desta migration não têm como ser reconstruídos (a informação não
-- era guardada em lugar nenhum), então a tabela começa vazia: o histórico passa a valer daqui
-- para frente.
