-- Celular vinculado ao cartão (2026-10-05): marcar presença pelo QR da sessão sem login. No
-- domingo de 04/10 cada leitura do QR caía no login, e boa parte dos assistidos não tem (ou não
-- lembra) login e senha. Agora o celular é vinculado UMA vez ao cartão e passa a marcar a própria
-- presença — e só isso: ele não abre o sistema (ver CelularVinculadoService).
--
-- O cookie do celular carrega um token aleatório de 256 bits; aqui fica só o SHA-256 dele. Com essa
-- entropia o SHA-256 basta (não é senha escolhida por gente, que precisaria de BCrypt), e é o que
-- permite achar o vínculo pelo hash. Um dump do banco não serve para marcar presença de ninguém.
CREATE TABLE celular_vinculado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assistido_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    vinculado_em TIMESTAMP NOT NULL,
    ultimo_uso_em TIMESTAMP,
    CONSTRAINT uk_celular_vinculado_token UNIQUE (token_hash),
    CONSTRAINT fk_celular_vinculado_assistido
        FOREIGN KEY (assistido_id) REFERENCES assistido(id) ON DELETE CASCADE
);

CREATE INDEX idx_celular_vinculado_assistido ON celular_vinculado (assistido_id);

-- Convite de vínculo gerado pela recepção (QR mostrado no prontuário): uso único e 10 minutos.
-- Também guardado como SHA-256. Um convite por assistido — gerar outro substitui o anterior.
ALTER TABLE assistido
    ADD COLUMN convite_celular_hash VARCHAR(64),
    ADD COLUMN convite_celular_expira_em TIMESTAMP;

CREATE UNIQUE INDEX uk_assistido_convite_celular ON assistido (convite_celular_hash);
