CREATE TABLE tipo_tratamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    como_funciona TEXT,
    objetivo_indicacao TEXT,
    triagem_observacoes TEXT
);

INSERT INTO tipo_tratamento (codigo, nome, como_funciona, objetivo_indicacao, triagem_observacoes) VALUES
('P1', 'Pasteur 1 – Tratamento Material Orgânico',
 'Doação de fluidos magnéticos vitais densos diretamente nas áreas afetadas do corpo físico.',
 'Auxiliar na restauração de tecidos, aliviar dores físicas e trazer conforto biológico.',
 'Necessita de entrevista prévia para avaliação do caso físico.'),

('P2', 'Pasteur 2 – Tratamento de Enfermidade Espiritual',
 'Atua no campo perispiritual e psíquico. Geralmente é o ponto de partida para a maioria dos assistidos.',
 'Dispersar fluidos negativos de pensamentos nocivos ou aproximações espirituais casuais, renovando a atmosfera psíquica.',
 'Necessita de entrevista prévia (porta de entrada para tratamentos específicos).'),

('P3A (ou P3F)', 'Tratamento Especializado (Físico Grave)',
 'Atendimento direcionado à saúde física em casos de extrema gravidade, sem necessidade de processo obsessivo.',
 'Casos de acidentes graves ou tratamento complementar de doenças severas (como o câncer).',
 'Necessita de triagem urgente e acompanhamento médico paralelo obrigatório.'),

('P3C', 'Tratamento Especializado (Depressão)',
 'Atuação profunda no campo fluídico e espiritual do assistido.',
 'Indicado para perturbações espirituais profundas com quadros graves de depressão e esgotamento fluídico severo.',
 'Necessita de entrevista prévia e avaliação cuidadosa do estado anímico.'),

('P3E', 'Desobsessão',
 'O paciente recebe fluidos na sala de passes enquanto uma equipe mediúnica (em sala reservada) doutrina o espírito obsessor.',
 'Casos de obsessão espiritual grave; visa o desligamento amoroso entre o obsessor e o paciente.',
 'Encaminhamento interno restrito após triagem profunda na entrevista.'),

('P3DC / P3V', 'Tratamento para Dependências e Vícios',
 'Atuação magnética no paciente e esclarecimento das entidades que se alimentam energeticamente dessas fraquezas.',
 'Casos graves de compulsões, dependência química e vícios (álcool, drogas, jogos).',
 'Necessita de entrevista prévia (foco no acolhimento e sigilo).'),

('A2', 'Assistência Evangélica',
 'Passe geral de harmonização aberto ao público. Dispensa entrevista prévia.',
 'Reequilíbrio espiritual e fluídico para o dia a dia.',
 'Dispensa entrevista prévia. Acesso livre e direto ao público.'),

('CH', 'Choque Anímico',
 'Passe rápido e de forte impacto magnético.',
 'Reerguer o tônico vital de forma imediata após uma queda vibratória brusca.',
 'Aplicação emergencial. Pode ser indicado pela triagem ou equipe de passes.'),

('P4', 'Série Infantil',
 'Passes adaptados especificamente para a sensibilidade dos pequenos.',
 'Atendimento espiritual e fluídico para bebês e crianças de até 10 ou 11 anos.',
 'Necessita de entrevista com os pais ou responsáveis legais.');
