-- Preletor convidado e cancelamento da preleção (2026-10-05, pedido do responsável do projeto).
--
-- O expositor pode ser um trabalhador da casa ou um CONVIDADO, que não é assistido: ele não tem
-- cartão, prontuário nem acesso, então fica numa tabela própria em vez de virar um assistido de
-- fachada. Guardamos só o necessário para contato (LGPD: nada além do que a escala precisa).
CREATE TABLE preletor_convidado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    telefone VARCHAR(30),
    email VARCHAR(150),
    -- Casa espírita ou instituição de onde vem.
    origem VARCHAR(150),
    observacoes TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT now()
);

-- A preleção passa a ter um trabalhador OU um convidado como preletor — exatamente um dos dois.
-- O convidado não some com a preleção (RESTRICT): a tela só exclui convidado que nunca preletou.
ALTER TABLE prelecao
    ALTER COLUMN trabalhador_id DROP NOT NULL,
    ADD COLUMN convidado_id BIGINT,
    ADD CONSTRAINT fk_prelecao_convidado FOREIGN KEY (convidado_id) REFERENCES preletor_convidado(id),
    ADD CONSTRAINT ck_prelecao_um_preletor CHECK (num_nonnulls(trabalhador_id, convidado_id) = 1);

CREATE INDEX idx_prelecao_convidado ON prelecao (convidado_id);

-- Cancelar = a preleção não vai acontecer, mas continua na escala (com o motivo) como registro.
-- Uma preleção cancelada libera a data para outra, e não é ligada às presenças da sessão.
ALTER TABLE prelecao
    ADD COLUMN cancelada_em TIMESTAMP,
    ADD COLUMN motivo_cancelamento VARCHAR(255);
